channel_sources:
  - conda-forge/label/cpptango_rc,conda-forge
channel_targets:
  - conda-forge tango-test_rc
# Build packages both for cpptango 9.3 and 9.4
# (osx only supported from 9.4)
cpptango:
  - 9.3    # [linux or win]
  - 9.4
