{% set name = "tango-test" %}
{% set version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoTest/-/archive/{{ version }}/TangoTest-{{ version }}.tar.gz
  sha256: 4111fe1499def4746b9d6d1830f2fbc9a21b785f80ba0b957795077fb68d02d1
  patches:
    - find-zeromq-win.patch  # [win]

build:
  number: 1

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - libtool                 # [unix]
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb
    - omniorb-libs

test:
  commands:
    # TangoTest --help returns 255, so grep the stderr for test
    - TangoTest --help 2>&1 | grep usage         # [unix]
    - TangoTest.exe --help 2>&1 | findstr usage  # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: TangoTest device server
  description: |
    This is the Tango-Controls TangoTest device server.
    A famous TANGO device server developed for testing.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/TangoTest
  doc_url: https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-try-tango.html#play-with-tango-controls
  doc_source_url: https://gitlab.com/tango-controls/TangoTest/tree/main/doc_html

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
